CREATE DATABASE IF NOT EXISTS `zef`;
use zef;

CREATE TABLE IF NOT EXISTS `users` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(64) DEFAULT NULL,
  `PASSWORD` varchar(128) DEFAULT NULL,
  `UQ` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `packages` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `VERSION` varchar(45) DEFAULT NULL,
  `OWNER` varchar(45) DEFAULT NULL,
  `REPO` varchar(1024) DEFAULT NULL,
  `SUBMITTED` timestamp DEFAULT CURRENT_TIMESTAMP,
  `COMMIT` varchar(64) DEFAULT NULL,
  `DOWNLOADS` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `zef`.`packages` ADD COLUMN `DEPENDENCIES` LONGTEXT NULL  AFTER `DOWNLOADS` ;


CREATE TABLE `tests` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` timestamp DEFAULT CURRENT_TIMESTAMP,
  `USER` varchar(45) DEFAULT NULL,
  `MODULE` varchar(45) DEFAULT NULL,
  `VERSION` varchar(45) DEFAULT NULL,
  `TESTDATA` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `downloads` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` timestamp DEFAULT CURRENT_TIMESTAMP,
  `PKG` varchar(45) DEFAULT NULL,
  `META` text DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

